# Generated by Django 4.2.6 on 2023-12-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_article_articlecategory_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favourite_categories",
            field=models.ManyToManyField(
                related_name="favourite_by", to="api.articlecategory"
            ),
        ),
    ]
