# Generated by Django 4.2.6 on 2023-12-13 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_article_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecomment",
            name="belongs_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
