# Generated by Django 4.2.6 on 2023-12-15 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_articlecomment_belongs_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="contents",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="articlecomment",
            name="belongs_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
